import type { Reference, ResearchDoc, Section, Comment, VersionEntry, JournalEntry, GraphNode, GraphLink } from './types';

export const references: Reference[] = [
  {
    id: 'ref-1',
    title: 'The Death and Life of Great American Cities',
    author: 'Jacobs, Jane',
    year: 1961,
    publisher: 'Random House',
    type: 'book',
    doi: '10.978/random/1961',
  },
  {
    id: 'ref-2',
    title: 'The Image of the City',
    author: 'Lynch, Kevin',
    year: 1960,
    publisher: 'MIT Press',
    type: 'book',
  },
  {
    id: 'ref-3',
    title: 'Urban Memory: An Archaeology of Spatial Recall',
    author: 'Rossi, Aldo',
    year: 1982,
    publisher: 'Oppositions Books',
    type: 'book',
  },
  {
    id: 'ref-4',
    title: 'Collage City',
    author: 'Rowe, Colin & Koetter, Fred',
    year: 1978,
    publisher: 'MIT Press',
    type: 'book',
  },
  {
    id: 'ref-5',
    title: 'Walkable City: How Downtown Can Save America',
    author: 'Speck, Jeff',
    year: 2012,
    publisher: 'Farrar, Straus and Giroux',
    type: 'book',
  },
  {
    id: 'ref-6',
    title: 'The Social Life of Small Urban Spaces',
    author: 'Whyte, William H.',
    year: 1980,
    publisher: 'Conservation Foundation',
    type: 'book',
  },
  {
    id: 'ref-7',
    title: 'Cognitive Mapping in an Urban Environment',
    author: 'Milgram, Stanley',
    year: 1972,
    publisher: 'Environment & Behavior',
    journal: 'Environment and Behavior',
    type: 'journal',
    doi: '10.1177/001391657200400402',
  },
  {
    id: 'ref-8',
    title: 'Toward an Architecture of Place',
    author: 'Sennett, Richard',
    year: 2018,
    publisher: 'Farrar, Straus and Giroux',
    type: 'book',
  },
];

export const researchDocs: ResearchDoc[] = [
  {
    id: 'doc-1',
    title: 'The Architecture of Urban Memory',
    subtitle: 'Research Paper',
    author: 'M. Chen',
    lastEdited: '14 min ago',
    citations: 23,
    status: 'Draft',
    type: 'Research Paper',
    category: 'My Research',
  },
  {
    id: 'doc-2',
    title: 'Urban Mobility Patterns in Post-Industrial Cities',
    subtitle: 'Research Paper',
    author: 'M. Chen',
    lastEdited: '2 hours ago',
    citations: 41,
    status: 'In Review',
    type: 'Research Paper',
    category: 'My Research',
  },
  {
    id: 'doc-3',
    title: 'Reading List: Phenomenology of Space',
    subtitle: 'Reading List',
    author: 'M. Chen',
    lastEdited: 'Yesterday',
    citations: 8,
    status: 'Draft',
    type: 'Reading List',
    category: 'My Research',
  },
  {
    id: 'doc-4',
    title: 'Field Report — Lisbon, March',
    subtitle: 'Field Report',
    author: 'M. Chen',
    lastEdited: '3 days ago',
    citations: 12,
    status: 'Published',
    type: 'Field Report',
    category: 'My Research',
  },
  {
    id: 'doc-5',
    title: 'Notes on Lynch and Cognitive Cartography',
    subtitle: 'Notes',
    author: 'M. Chen',
    lastEdited: '1 week ago',
    citations: 5,
    status: 'Draft',
    type: 'Notes',
    category: 'My Research',
  },
  {
    id: 'doc-6',
    title: 'The Street as Public Memory',
    subtitle: 'Essay',
    author: 'M. Chen',
    lastEdited: '1 week ago',
    citations: 17,
    status: 'Archived',
    type: 'Essay',
    category: 'My Research',
  },
];

export const sections: Section[] = [
  { id: 'sec-intro', number: '01', title: 'Introduction', level: 1 },
  { id: 'sec-lit', number: '02', title: 'Literature Review', level: 1 },
  { id: 'sec-method', number: '03', title: 'Methodology', level: 1 },
  { id: 'sec-results', number: '04', title: 'Results', level: 1 },
  { id: 'sec-disc', number: '05', title: 'Discussion', level: 1 },
  { id: 'sec-conc', number: '06', title: 'Conclusion', level: 1 },
];

export const comments: Comment[] = [
  {
    id: 'c1',
    author: 'Sarah Lindqvist',
    initials: 'SL',
    color: '#6b7d99',
    text: 'Expand the methodology section — the sample size justification is thin here.',
    time: '14 min ago',
    resolved: false,
    highlight: 'The study examines three districts over a twelve-month period.',
  },
  {
    id: 'c2',
    author: 'Daniel Okafor',
    initials: 'DO',
    color: '#4f6f4f',
    text: 'Consider adding Rossi here to strengthen the theoretical framing.',
    time: '1 hour ago',
    resolved: false,
    highlight: 'Cities preserve memory through form, not merely function.',
  },
  {
    id: 'c3',
    author: 'Sarah Lindqvist',
    initials: 'SL',
    color: '#6b7d99',
    text: 'This citation format looks correct now — verified against the journal style guide.',
    time: 'Yesterday',
    resolved: true,
    highlight: '[12]',
  },
];

export const versionHistory: VersionEntry[] = [
  { id: 'v1', time: '14:42', label: 'Methodology updated', group: 'Today' },
  { id: 'v2', time: '13:08', label: '3 citations added', group: 'Today' },
  { id: 'v3', time: '11:30', label: 'Abstract revised', group: 'Today' },
  { id: 'v4', time: '18:31', label: 'Introduction rewritten', group: 'Yesterday' },
  { id: 'v5', time: '15:20', label: 'Results section expanded', group: 'Yesterday' },
  { id: 'v6', time: '09:12', label: 'Initial draft', group: 'Monday' },
];

export const journalEntries: JournalEntry[] = [
  {
    id: 'j1',
    title: 'On the Slow Erosion of Public Space',
    author: 'M. Chen',
    excerpt: 'A meditation on how the privatization of urban corridors reshapes collective memory — and what we lose when streets become corridors of consumption rather than encounter.',
    date: 'Aug 24, 2026',
    readTime: '12 min',
    tag: 'Essay',
  },
  {
    id: 'j2',
    title: 'Reading Lynch in the Age of Spatial Computing',
    author: 'D. Okafor',
    excerpt: 'Kevin Lynch asked how cities become legible in the mind. Sixty years later, we carry that legibility in our pockets — and the city has learned to read us back.',
    date: 'Aug 21, 2026',
    readTime: '8 min',
    tag: 'Research Note',
  },
  {
    id: 'j3',
    title: 'Field Report: Walking the Alfama',
    author: 'S. Lindqvist',
    excerpt: 'Three days of systematic observation in Lisbon\'s oldest district. Notes on rhythm, threshold, and the texture of stone worn smooth by five centuries of feet.',
    date: 'Aug 18, 2026',
    readTime: '15 min',
    tag: 'Field Report',
  },
  {
    id: 'j4',
    title: 'A Reading List for Phenomenology of Place',
    author: 'M. Chen',
    excerpt: 'Twelve texts that shaped how I think about embodied space — from Bachelard\'s poetics to Merleau-Ponty\'s body, with a few surprises along the way.',
    date: 'Aug 15, 2026',
    readTime: '5 min',
    tag: 'Reading List',
  },
];

export const graphNodes: GraphNode[] = [
  { id: 'n1', label: 'Urban Memory', type: 'paper', x: 50, y: 50 },
  { id: 'n2', label: 'Lynch — Image of City', type: 'reference', x: 20, y: 25 },
  { id: 'n3', label: 'Rossi — Architecture', type: 'reference', x: 80, y: 28 },
  { id: 'n4', label: 'Jacobs — Death & Life', type: 'reference', x: 78, y: 72 },
  { id: 'n5', label: 'Cognitive Mapping', type: 'note', x: 25, y: 78 },
  { id: 'n6', label: 'M. Chen', type: 'author', x: 50, y: 15 },
  { id: 'n7', label: 'Mobility Study', type: 'paper', x: 88, y: 50 },
  { id: 'n8', label: 'Urban Lab', type: 'project', x: 12, y: 50 },
  { id: 'n9', label: 'Walkability Notes', type: 'note', x: 35, y: 90 },
  { id: 'n10', label: 'Speck — Walkable City', type: 'reference', x: 65, y: 90 },
];

export const graphLinks: GraphLink[] = [
  { from: 'n1', to: 'n2' },
  { from: 'n1', to: 'n3' },
  { from: 'n1', to: 'n4' },
  { from: 'n1', to: 'n5' },
  { from: 'n1', to: 'n6' },
  { from: 'n1', to: 'n7' },
  { from: 'n1', to: 'n8' },
  { from: 'n5', to: 'n9' },
  { from: 'n7', to: 'n4' },
  { from: 'n7', to: 'n10' },
  { from: 'n9', to: 'n10' },
  { from: 'n3', to: 'n8' },
];

export const labMembers = [
  { initials: 'MC', name: 'M. Chen', role: 'Principal Investigator', color: '#3a4a63' },
  { initials: 'SL', name: 'S. Lindqvist', role: 'Postdoctoral Researcher', color: '#6b7d99' },
  { initials: 'DO', name: 'D. Okafor', role: 'PhD Candidate', color: '#4f6f4f' },
  { initials: 'RP', name: 'R. Park', role: 'Research Assistant', color: '#b8893a' },
  { initials: 'AK', name: 'A. Kovač', role: 'Visiting Scholar', color: '#a2533a' },
];

export const citationStyles: Record<string, (r: Reference) => string> = {
  APA: (r) => `${r.author} (${r.year}). ${r.title}. ${r.publisher}.`,
  MLA: (r) => `${r.author}. ${r.title}. ${r.publisher}, ${r.year}.`,
  Chicago: (r) => `${r.author}. ${r.title}. ${r.publisher}, ${r.year}.`,
  IEEE: (r) => `[12] ${r.author}, ${r.title}. ${r.publisher}, ${r.year}.`,
};
